// packages/frontend-solid/src/components/layouts/dashboard/layout.tsx
import type { ParentComponent } from 'solid-js';
import { Header } from '@/components/header/header';

/** Suspense/loading variant of the dashboard layout (no auth data yet) */
export const DashboardLayoutSuspense: ParentComponent = (props) => {
  return (
    <div class="flex bg-background overflow-hidden w-screen flex-col" style={{ height: 'calc(100vh - var(--titlebar-height, 0px))' }}>
      <Header isLoggedIn={false} isUpdateAvailable={false} />
      <div class="flex flex-1 flex-col pt-24 px-4 container mx-auto h-full overflow-y-auto">
        <div class="rounded-xl border bg-card text-card-foreground shadow p-6">{props.children}</div>
      </div>
    </div>
  );
};

/** Main authenticated dashboard layout */
export const DashboardLayout: ParentComponent<{
  isLoggedIn: boolean;
  isUpdateAvailable: boolean;
}> = (props) => {
  return (
    <div class="flex bg-background overflow-hidden w-screen flex-col" style={{ height: 'calc(100vh - var(--titlebar-height, 0px))' }}>
      <Header isLoggedIn={props.isLoggedIn} isUpdateAvailable={props.isUpdateAvailable} />

      <main class="flex-1 relative pt-24 px-4 container mx-auto h-full overflow-y-auto overflow-x-hidden">{props.children}</main>
    </div>
  );
};

// packages/frontend/src/components/layouts/dashboard/layout.tsx
import { Header } from '@/components/header/header';
import { type PropsWithChildren, useEffect, useRef } from 'react';
import semver from 'semver';
import { useAppContext } from '@/context/app-context';
import { useUserContext } from '@/context/user-context';
import { AnimatePresence, motion } from 'framer-motion';
import { useLocation, Navigate } from 'react-router';

export const DashboardLayoutSuspense = ({ children }: PropsWithChildren) => {
  return (
    <div className="flex bg-background overflow-hidden w-screen flex-col" style={{ height: 'calc(100vh - var(--titlebar-height, 0px))' }}>
      <Header isLoggedIn={false} isUpdateAvailable={false} allowAutoThemes={false} />
      <div className="flex flex-1 flex-col pt-24 px-4 container mx-auto h-full overflow-y-auto no-scrollbar">
        <div className="rounded-xl border bg-card text-card-foreground shadow p-6">{children}</div>
      </div>
    </div>
  );
};

export const DashboardLayout = ({ children }: PropsWithChildren) => {
  const { user, userSettings, version } = useAppContext();
  const location = useLocation();
  const prevPathRef = useRef(location.pathname);
  const { isLoggedIn } = useUserContext();

  useEffect(() => {
    prevPathRef.current = location.pathname;
  }, [location.pathname]);

  // Version check logic
  let isLatest = false;
  try {
    isLatest = (semver.valid(version?.current) && semver.valid(version?.latest) && semver.gte(version.current, version.latest)) || false;
  } catch (_e) {
    // ignore semver errors
  }

  if (version?.current === 'nightly') {
    isLatest = true;
  }

  // Redirect to onboarding if not completed
  if (!user.hasCompletedOnboarding && !location.pathname.startsWith('/onboarding')) {
    return <Navigate to="/onboarding" replace />;
  }

  // Transition logic
  const getDepth = (path: string) => {
    if (path === '/dashboard') return 0;
    if (path.startsWith('/apps') || path.startsWith('/app-store') || path.startsWith('/settings')) {
      const parts = path.split('/').filter(Boolean);
      if (parts.length > 1 && (parts[0] === 'apps' || parts[0] === 'app-store')) return 2;
      return 1;
    }
    return 1;
  };

  const currentDepth = getDepth(location.pathname);
  const prevDepth = getDepth(prevPathRef.current);
  let direction = 0;

  if (currentDepth > prevDepth) direction = 1;
  else if (currentDepth < prevDepth) direction = -1;

  const variants = {
    enter: (direction: number) => ({
      x: direction > 0 ? 1000 : -1000,
      opacity: 0,
    }),
    center: {
      zIndex: 1,
      x: 0,
      opacity: 1,
    },
    exit: (direction: number) => ({
      zIndex: 0,
      x: direction < 0 ? 1000 : -1000,
      opacity: 0,
    }),
  };

  return (
    <div className="flex bg-background overflow-hidden w-screen flex-col" style={{ height: 'calc(100vh - var(--titlebar-height, 0px))' }}>
      <Header isLoggedIn={isLoggedIn} isUpdateAvailable={!isLatest} allowAutoThemes={userSettings.allowAutoThemes} />

      <main className="flex-1 relative pt-24 px-4 container mx-auto h-full overflow-y-auto overflow-x-hidden no-scrollbar">
        <AnimatePresence mode="popLayout" custom={direction}>
          <motion.div
            key={location.pathname}
            custom={direction}
            variants={variants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{
              x: { type: 'spring', stiffness: 300, damping: 30 },
              opacity: { duration: 0.2 },
            }}
            className="w-full h-full"
          >
            {children}
          </motion.div>
        </AnimatePresence>
      </main>
    </div>
  );
};
