// packages/frontend/src/components/header/header.tsx
import { Link, NavLink, useNavigate } from 'react-router';
import { LogOut, Home, Settings, Store, Menu, LogIn, Sun, Moon } from 'lucide-react';
import { clsx } from 'clsx';
import { useTranslation } from 'react-i18next';
import { Button, buttonVariants } from '@/components/ui/Button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  DropdownMenuPortal,
  DropdownMenuTrigger,
} from '@/components/ui/DropdownMenu';
import { ModeToggle } from '@/components/mode-toggle';
import { useTheme } from '@/components/providers/theme/theme-provider';
import { useUserContext } from '@/context/user-context';
import { useMutation } from '@tanstack/react-query';
import { logoutMutation } from '@/api-client/@tanstack/react-query.gen';

type HeaderProps = {
  isUpdateAvailable?: boolean;
  isLoggedIn?: boolean;
  allowAutoThemes?: boolean;
};

export const Header = (props: HeaderProps) => {
  const userContext = useUserContext();
  const { setTheme } = useTheme();
  // Prefer context for authentication state
  const isLoggedIn = props.isLoggedIn ?? userContext.isLoggedIn;

  const navigate = useNavigate();
  const { t } = useTranslation();

  const logout = useMutation({
    ...logoutMutation(),
    onSuccess: () => {
      window.location.reload();
    },
  });

  const handleLogout = () => {
    logout.mutate({});
  };

  // Common NavLink classes logic
  const getNavLinkClass = ({ isActive }: { isActive: boolean }) =>
    clsx(buttonVariants({ variant: 'ghost', size: 'sm' }), 'cursor-pointer', isActive ? 'bg-accent text-accent-foreground btn-active' : '');

  return (
    <header
      className="fixed left-1/2 z-50 flex h-14 w-[96%] md:w-[77%] lg:w-[70%] xl:w-[53%] -translate-x-1/2 items-center gap-2 rounded-full border bg-background/80 px-3 shadow-md backdrop-blur-md"
      style={{ top: 'calc(var(--titlebar-height, 0px) + 1rem)' }}
    >
      {/* Logo (Left) */}
      <div className="flex items-center justify-start">
        <Link to="/dashboard" className="flex items-center">
          <img
            src="/2024_CI__Logo_Banner_Color_small.svg"
            alt="Companion Intelligence Logo"
            className="h-9 w-auto object-contain hidden dark:block"
          />
          <img
            src="/2024_CI__Logo_Banner_Color_small-lightmode2.svg"
            alt="Companion Intelligence Logo"
            className="h-9 w-auto object-contain block dark:hidden"
          />
        </Link>
      </div>

      {/* Navigation (Center) — aligned with CI Portal (absolute center, lg+ only) */}
      {isLoggedIn && (
        <nav className="absolute left-1/2 -translate-x-1/2 hidden lg:flex items-center justify-center gap-2">
          <NavLink to="/dashboard" className={getNavLinkClass}>
            <Home className="mr-2 size-4" />
            Home
          </NavLink>
          <NavLink to="/app-store" className={getNavLinkClass}>
            <Store className="mr-2 size-4" />
            Store
          </NavLink>
        </nav>
      )}

      {/* User Actions (Right) - Desktop */}
      <div className="hidden lg:flex items-center justify-end gap-2 ml-auto">
        <ModeToggle />

        {!isLoggedIn && (
          <Button variant="ghost" size="sm" onClick={() => navigate('/login')}>
            {t('login', 'Login')}
            <LogIn className="ml-2 size-4" />
          </Button>
        )}

        {isLoggedIn && (
          <>
            {/* Settings Link */}
            <NavLink
              to="/settings"
              title={t('HEADER_SETTINGS', 'Settings')}
              className={({ isActive }) =>
                clsx(buttonVariants({ variant: 'ghost', size: 'icon' }), isActive ? 'bg-accent text-accent-foreground btn-active' : '')
              }
            >
              <Settings className="size-4" />
              <span className="sr-only">{t('HEADER_SETTINGS', 'Settings')}</span>
            </NavLink>

            <Button variant="ghost" size="icon" title={t('HEADER_LOGOUT', 'Logout')} onClick={handleLogout}>
              <LogOut className="size-4" />
              <span className="sr-only">{t('HEADER_LOGOUT', 'Logout')}</span>
            </Button>
          </>
        )}
      </div>

      {/* Mobile Menu (Right) */}
      <div className="flex lg:hidden justify-end ml-auto">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon">
              <Menu className="size-5" />
              <span className="sr-only">Open menu</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-56">
            {isLoggedIn ? (
              <>
                <DropdownMenuItem asChild>
                  <Link to="/dashboard" className="w-full cursor-pointer flex items-center">
                    <Home className="mr-2 size-4" />
                    Home
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link to="/app-store" className="w-full cursor-pointer flex items-center">
                    <Store className="mr-2 size-4" />
                    Store
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem asChild>
                  <Link to="/settings" className="w-full cursor-pointer flex items-center">
                    <Settings className="mr-2 size-4" />
                    {t('HEADER_SETTINGS', 'Settings')}
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuSub>
                  <DropdownMenuSubTrigger>
                    <div className="relative mr-2 size-4">
                      <Sun className="absolute size-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                      <Moon className="absolute size-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
                    </div>
                    <span>Theme</span>
                  </DropdownMenuSubTrigger>
                  <DropdownMenuPortal>
                    <DropdownMenuSubContent>
                      <DropdownMenuItem onClick={() => setTheme('light')}>Light</DropdownMenuItem>
                      <DropdownMenuItem onClick={() => setTheme('dark')}>Dark</DropdownMenuItem>
                      <DropdownMenuItem onClick={() => setTheme('system')}>System</DropdownMenuItem>
                    </DropdownMenuSubContent>
                  </DropdownMenuPortal>
                </DropdownMenuSub>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={handleLogout} className="cursor-pointer flex items-center text-red-600 focus:text-red-600">
                  <LogOut className="mr-2 size-4" />
                  {t('HEADER_LOGOUT', 'Logout')}
                </DropdownMenuItem>
              </>
            ) : (
              <DropdownMenuItem onClick={() => navigate('/login')} className="cursor-pointer flex items-center">
                <LogIn className="mr-2 size-4" />
                {t('login', 'Login')}
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
};

// packages/frontend-solid/src/components/header/header.tsx
import { A, useLocation } from '@solidjs/router';
import { Show } from 'solid-js';
import { clsx } from 'clsx';
import { Home, Store, Settings, LogOut, LogIn, Menu } from 'lucide-solid';
import { Button, buttonVariants } from '@/components/ui/Button';
import { ModeToggle } from '@/components/mode-toggle';
import { useUserContext } from '@/context/user-context';
import { api } from '@/api-client';
import { createSignal } from 'solid-js';

interface HeaderProps {
  isLoggedIn?: boolean;
  isUpdateAvailable?: boolean;
}

export function Header(props: HeaderProps) {
  const { userContext } = useUserContext();
  const location = useLocation();
  const [mobileOpen, setMobileOpen] = createSignal(false);

  const isLoggedIn = () => props.isLoggedIn ?? userContext().isLoggedIn;

  const handleLogout = async () => {
    try {
      await api.logout();
    } finally {
      window.location.reload();
    }
  };

  const navLinkClass = (path: string) =>
    clsx(
      buttonVariants({ variant: 'ghost', size: 'sm' }),
      'cursor-pointer',
      location.pathname.startsWith(path) ? 'bg-accent text-accent-foreground' : '',
    );

  return (
    <header
      class="fixed left-1/2 z-50 flex h-14 w-[96%] md:w-[77%] lg:w-[70%] xl:w-[53%] -translate-x-1/2 items-center gap-2 rounded-full border bg-background/80 px-3 shadow-md backdrop-blur-md"
      style={{ top: 'calc(var(--titlebar-height, 0px) + 1rem)' }}
    >
      {/* Logo */}
      <div class="flex items-center justify-start">
        <A href="/dashboard" class="flex items-center">
          <img src="/2024_CI__Logo_Banner_Color_small.svg" alt="Companion Intelligence Logo" class="h-9 w-auto object-contain hidden dark:block" />
          <img
            src="/2024_CI__Logo_Banner_Color_small-lightmode2.svg"
            alt="Companion Intelligence Logo"
            class="h-9 w-auto object-contain block dark:hidden"
          />
        </A>
      </div>

      {/* Desktop Nav */}
      <Show when={isLoggedIn()}>
        <nav class="absolute left-1/2 -translate-x-1/2 hidden lg:flex items-center justify-center gap-2">
          <A href="/dashboard" class={navLinkClass('/dashboard')}>
            <Home class="mr-2 size-4" />
            Home
          </A>
          <A href="/app-store" class={navLinkClass('/app-store')}>
            <Store class="mr-2 size-4" />
            Store
          </A>
        </nav>
      </Show>

      {/* Desktop Right Actions */}
      <div class="hidden lg:flex items-center justify-end gap-2 ml-auto">
        <ModeToggle />

        <Show when={!isLoggedIn()}>
          <A href="/login" class={buttonVariants({ variant: 'ghost', size: 'sm' })}>
            Login
            <LogIn class="ml-2 size-4" />
          </A>
        </Show>

        <Show when={isLoggedIn()}>
          <A
            href="/settings"
            title="Settings"
            class={clsx(
              buttonVariants({ variant: 'ghost', size: 'icon' }),
              location.pathname.startsWith('/settings') ? 'bg-accent text-accent-foreground' : '',
            )}
          >
            <Settings class="size-4" />
            <span class="sr-only">Settings</span>
          </A>
          <Button variant="ghost" size="icon" title="Logout" onClick={handleLogout}>
            <LogOut class="size-4" />
            <span class="sr-only">Logout</span>
          </Button>
        </Show>
      </div>

      {/* Mobile Menu */}
      <div class="flex lg:hidden justify-end ml-auto relative">
        <Button variant="ghost" size="icon" onClick={() => setMobileOpen(!mobileOpen())}>
          <Menu class="size-5" />
          <span class="sr-only">Open menu</span>
        </Button>

        <Show when={mobileOpen()}>
          <div class="absolute top-full right-0 mt-2 w-56 rounded-md border bg-popover p-1 shadow-md">
            <Show when={isLoggedIn()}>
              <A href="/dashboard" class="flex items-center p-2 rounded-sm hover:bg-accent" onClick={() => setMobileOpen(false)}>
                <Home class="mr-2 size-4" />
                Home
              </A>
              <A href="/app-store" class="flex items-center p-2 rounded-sm hover:bg-accent" onClick={() => setMobileOpen(false)}>
                <Store class="mr-2 size-4" />
                Store
              </A>
              <div class="my-1 h-px bg-border" />
              <A href="/settings" class="flex items-center p-2 rounded-sm hover:bg-accent" onClick={() => setMobileOpen(false)}>
                <Settings class="mr-2 size-4" />
                Settings
              </A>
              <div class="my-1 h-px bg-border" />
              <button
                type="button"
                class="flex items-center p-2 rounded-sm hover:bg-accent w-full text-left text-red-600"
                onClick={() => {
                  setMobileOpen(false);
                  handleLogout();
                }}
              >
                <LogOut class="mr-2 size-4" />
                Logout
              </button>
            </Show>
            <Show when={!isLoggedIn()}>
              <A href="/login" class="flex items-center p-2 rounded-sm hover:bg-accent" onClick={() => setMobileOpen(false)}>
                <LogIn class="mr-2 size-4" />
                Login
              </A>
            </Show>
          </div>
        </Show>
      </div>
    </header>
  );
}
