// packages/frontend-solid/src/context/user-context.tsx
import { createContext, useContext, type ParentComponent } from 'solid-js';
import { createResource } from 'solid-js';
import { api, type UserContextDto } from '@/api-client';

const USER_CONTEXT_DEFAULTS: UserContextDto = {
  isLoggedIn: false,
  isPasswordResetDisabled: false,
  isGuestDashboardEnabled: false,
  isConfigured: false,
  domain: '',
  localDomain: '',
  sslPort: 443,
  allowErrorMonitoring: false,
  allowAutoThemes: false,
  themeBase: 'gray',
  themeColor: 'blue',
  version: { current: '0.0.0', latest: '0.0.0', body: '', releases: [] },
};

interface UserContextValue {
  userContext: () => UserContextDto;
  isLoading: () => boolean;
  refetch: () => void;
}

const UserCtx = createContext<UserContextValue>();

export const UserContextProvider: ParentComponent = (props) => {
  const [data, { refetch }] = createResource(() => api.getUserContext(), {
    initialValue: USER_CONTEXT_DEFAULTS,
  });

  const value: UserContextValue = {
    userContext: () => data() ?? USER_CONTEXT_DEFAULTS,
    isLoading: () => data.loading,
    refetch: () => {
      refetch();
    },
  };

  return <UserCtx.Provider value={value}>{props.children}</UserCtx.Provider>;
};

export const useUserContext = () => {
  const ctx = useContext(UserCtx);
  if (!ctx) throw new Error('useUserContext must be used within UserContextProvider');
  return ctx;
};

// packages/frontend/src/context/user-context.tsx
import type { UserContextDto } from '@/api-client';
import { userContextOptions, userContextQueryKey } from '@/api-client/@tanstack/react-query.gen';
import { useQueryClient, useQuery } from '@tanstack/react-query';
import { createContext, useContext } from 'react';

interface UserContextValue extends UserContextDto {
  refreshUserContext: () => Promise<void>;
  setUserContext: (newUserContext: Partial<UserContextDto>) => void;
  isLoading: boolean;
}

const UserContext = createContext<UserContextValue | null>(null);

const USER_CONTEXT_DEFAULTS: UserContextDto = {
  isLoggedIn: false,
  isPasswordResetDisabled: false,
  isGuestDashboardEnabled: false,
  isConfigured: false,
  domain: '',
  localDomain: '',
  sslPort: 443,
  allowErrorMonitoring: false,
  allowAutoThemes: false,
  themeColor: 'blue',
  themeBase: 'gray',
  version: { current: '0.0.0', latest: '0.0.0', body: '', releases: [] },
} as UserContextDto;

export const UserContextProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const queryClient = useQueryClient();

  const queryKey = userContextQueryKey();
  const {
    data: userContext,
    error,
    isFetching,
    isLoading,
  } = useQuery({
    ...userContextOptions(),
    staleTime: 30_000,
  });

  if (error && !isFetching) {
    throw error;
  }

  const refreshUserContext = async () => {
    await queryClient.invalidateQueries({ queryKey });
  };

  const resolvedContext = userContext ?? USER_CONTEXT_DEFAULTS;

  const value = {
    ...resolvedContext,
    isLoading,
    refreshUserContext: refreshUserContext,
    setUserContext: (newUserContext: Partial<UserContextDto>) => {
      queryClient.setQueryData(['userContext'], { ...resolvedContext, ...newUserContext });
    },
  };

  return <UserContext.Provider value={value}>{children}</UserContext.Provider>;
};

export const useUserContext = () => {
  const context = useContext(UserContext);
  if (context === null) {
    throw new Error('useUserContext must be used within an UserContextProvider');
  }
  return context;
};
